### ISSUE TITLE
Add edit roles "anyone with the link"

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#238]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
I can only add roles to people by inviting them one by one. 
Sometimes my doc is not that sensitive.

**Describe the solution you'd like**
I'd like to enable edit for people who have the link. 

**Describe alternatives you've considered**
Invite people one by one

**Discovery, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs (if applicable).
Maybe a screenshot or design?
If my doc is not public, I need to sign in to see it.
If my doc is public and edit is available to anyone with the link, then anyone can edit it.

**Do you want to work on it through a Pull Request?**

**Comment by AntoLC** [comment]
Yes you're right.

We are working on this feature: https://github.com/numerique-gouv/impress/pull/234

**Comment by virgile-dev** [comment]
Hey @AntoLC 
Just out from a call with Arnaud.
He stressed out the importance of this feature. It really is the main pain point we have for docs for two reasons.
- Users may not know who to invite on the doc and need a sharing link that's someone secure
- It's tedious to invite a lot of people on a doc 
If you can tackle it in priority when you're back from vacation that's great.
