### ISSUE TITLE
One click doc creation

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#272]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Doc creation should have the shortest path possible.
Users want to click create and start writing. 
That's what they are here for. 
Configuration (sharing, access etc.) usually comes later.

**Describe the solution you'd like**
- [x] Get rid of the modal. A click on the "Create" should get the user to the doc edition page

So what happens with the title 
- [x] As a user I want to be able to edit the title by clicking on the input field 
- [x] Put a grey place holder "Without title"
- [ ] If the user doesn't input any title, the tile becomes the first line of the doc

**Mockup**
- To edit the title the user clicks on "Sans titre", as soon as he clicks elsewhere or hits enter it's saved
![Capture d’écran du 2024-09-20 10-32-47](https://github.com/user-attachments/assets/bf2c7ae3-12bd-4c70-981c-bdb7a14c8403)

**Comment by arnaud-robin** [comment]
#275
