### ISSUE TITLE
Store user first and last name from the SSO provider

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#293]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Right now we only keep the user email.

**Describe the solution you'd like**
It'd be nice to also have its firstname and lastname so that we have a shorter thing to display in emails, the cursor showing who else is editing the doc etc.

**Comment by AntoLC** [comment]
Duplicate of: https://github.com/numerique-gouv/impress/issues/289

**Comment by virgile-dev** [comment]
Oups sorry ! Closing
