### ISSUE TITLE
✨Export to markdown and HTML

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/impress#300]
## Feature Proposal

We can easily export the document to markdown or html.

We could add 2 buttons, "Copy to markdown" and "Copy to html" that will copy the editor in your clipboard to paste it where you want.

See: https://www.blocknotejs.org/docs/editor-api/converting-blocks

![image](https://github.com/user-attachments/assets/a4f1c33b-3c43-4170-9ba3-a2b314f31872)

## Dropdown code location

https://github.com/numerique-gouv/impress/blob/39d0211593511dd1030264f9a7e37e57cab1bce8/src/frontend/apps/impress/src/features/docs/doc-header/components/DocToolBox.tsx#L67-L130

**Comment by rvveber** [comment]
I would like to implement this.
Can it be assigned to me?

**Comment by rvveber** [comment]
The feature was implemented, it is ready for review

**Comment by rvveber** [comment]
Finally was able to run the tests locally without issues.
For future tickets, i now know what to look for and what conventions are in place.

You may review.
Thanks!
