### ISSUE TITLE
Unify frontend and backend language preference using shared cookie

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#333]
## Bug Report

**Problematic behavior**
Here you can see "Doc private" appears in English but the user interface is in French. 
https://github.com/user-attachments/assets/0ae0e457-15f7-423c-b4bc-c1c5fc9d48bc

Same when I'm loading a doc I don't have access to. The message only is available in French even if I sent the interface in English and reload.
![Capture d’écran du 2024-10-14 17-26-11](https://github.com/user-attachments/assets/0646afd7-f25a-4e9d-b7fe-2b7a6457db33)

**Comment by rvveber** [comment]
This seems to be an issue with the backend not beeing communicated the current language to.

Here is how Django determines the current language:
https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#how-django-discovers-language-preference

> First, it looks for the language prefix in the requested URL. This is only performed when you are using the i18n_patterns function in your root URLconf. See [Internationalization: in URL patterns](https://docs.djangoproject.com/en/5.1/topics/i18n/translation/#url-internationalization) for more information about the language prefix and how to internationalize URL patterns.

> Failing that, it looks for a cookie.

> The name of the cookie used is set by the [LANGUAGE_COOKIE_NAME](https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-LANGUAGE_COOKIE_NAME) setting. (The default name is django_language.)

> Failing that, it looks at the Accept-Language HTTP header. This header is sent by your browser and tells the server which language(s) you prefer, in order by priority. Django tries each language in the header until it finds one with available translations.

> Failing that, it uses the global [LANGUAGE_CODE](https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-LANGUAGE_CODE) setting.

For me the message is always english, which means that Django probably determines it by 
`Accept-Language HTTP header`.

We currently dont use language patterns `/fr` in the url

So the best option, would be to set a cookie with the language code when switching the language in the frontend. The default name of the cookie is `django_language` but the name is configurable via the setting `LANGUAGE_COOKIE_NAME`

Next.JS accepts a special cookie which needs to be called `NEXT_LOCALE`
https://nextjs.org/docs/pages/building-your-application/routing/internationalization#leveraging-the-next_locale-cookie
We could set this cookie on language change and configure django to use the same cookie to determine the current language. Making the sure frontend and backend have a persistable user preferred language

**Comment by rvveber** [comment]
The implementation is finished.
It may be reviewed.
