### ISSUE TITLE
Make AI model configurable

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#334]
## Bug Report

**Problematic behavior**
Right now it's an env variable

**Expected behavior/code**
Make it something configurable.  
@arnaud-robin what did you have in mind ? Should it be at the user level (user can choose between several models) or at the admin level (admin chooses the model for the users from the admin panel by entering an API key)

**Comment by AntoLC** [comment]
It is already configurable actually:
https://github.com/numerique-gouv/impress/pull/250/files#diff-f7f92c796b1a33dc13bcae226f8d09a836e102c271a36b494c12613152126d73R11-R19
