### ISSUE TITLE
♻️Add name next to email

### ISSUE THREAD

**Issue by AntoLC** [numerique-gouv/impress#337]
## Feature Request

We recently got the username from the backend, use it instead of the email.

![image](https://github.com/user-attachments/assets/f9125cca-4af6-47b1-b940-c5c4ce651f4e)
![image](https://github.com/user-attachments/assets/4d40d89f-6262-41b1-baf1-c97f2c583414)

**Comment by leonardopaloschi** [comment]
Hey @AntoLC , I would love to help solve this issue.
Could you help me understand which part of the backend the information comes from and in which file this user needs to be received and displayed?

**Comment by virgile-dev** [comment]
Let 's have the name and the email on two lines. Because emails are a good way to know from which org the user is.
First Name 
first.name@email.com

**Comment by leonardopaloschi** [comment]
Hi, @virgile-dev! Could you help me with the questions I asked in my last comment?
