### ISSUE TITLE
✨ Silent login

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#362]
## Bug Report

**Problematic behavior**
Stéphanie complained that she has to login on mobile everytime she doesn't docs for a while. 
For an app like Docs, users expect their session to last a while. Having to login everytime they don't use it for 2 days is not optimal.

**Expected behavior/code**
The purpose of silent login is that you log in with 1 click once a day on proconnect, then all your sites are connected without having to click on login again.
@lebaudantoine Samuel said you worked on that can you give us pointers ?

**Comment by lebaudantoine** [comment]
Yes I did in Visio, can do in Docs if you are okay. I prefer open a PR and then you review it instead of giving you pointers

**Comment by lebaudantoine** [comment]
> For an app like Docs, users expect their session to last a while. Having to login everytime they don't use it for 2 days is not optimal.

This is another kind of problem … this is related to the length of the pro connect session, currently, a user would be forced to log in every 12hours

**Comment by virgile-dev** [comment]
> Yes I did it in Visio, can do in Docs if you are okay. I would prefer to open a PR, and then you review it instead of giving you pointers. (I am talking of silently log the user)

Please go ahead :)
