### ISSUE TITLE
🐛 public -> private, users can see updates if they don't refresh the page

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#383]
## Bug Report

**Problematic behavior**
User who opened a doc when it was public and don't refresh can see updates even if the document was made private.

**Expected behavior/code**
If the doc visibility changes from public to private it should affect users consulting the doc in real time. 
So maybe we should force a refresh or find some kind of viable solution.

**Additional context/Screenshots**
https://www.loom.com/share/43d66acf412641e5893402e99445fcd0?sid=08ccd38d-4a82-48d4-8eef-dc0e998fa5f8

**Comment by AntoLC** [comment]
Lot of "IF":
- if someone has a doc in public
- if the owner switch to private
- if at the same moment someone that was invited thanks to the public link is connected on the doc
- if you decide to add some super secrets

To solve that, basically the backend should send the information to the frontend, so to address this potential bug, you must add websocket, or a webhook system, or pulling but we don't want that. We could try to use the y.js server to send this information, but it is a bit like a trick.

**Comment by AntoLC** [comment]
If we want this level of security, another case:
- I invite userA
- userA connect to the doc
- I revoke userA
- userA can still see the doc until he refreshed the page
