### ISSUE TITLE
Add export option without template

### ISSUE THREAD

**Issue by virgile-dev** [numerique-gouv/impress#396]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Right now the default template adds the French Republic logo at the top of the doc. Problem is this is the only template we have. Not everything I write is an official document.

**Describe the solution you'd like**
We should have an export option with no template.

**Comment by AntoLC** [comment]
![image](https://github.com/user-attachments/assets/cf5d0597-a691-460d-8ede-a1e1658c30dd)
