### ISSUE TITLE
Initial document creation

### ISSUE THREAD

**Issue by YousefED** [numerique-gouv/impress#471]
(I found this while investigating the freeze issue, but it might not be directly related to that)

## Bug Report

When opening the document "Room record" (or creating a new document) and opening this in a new tab without making any changes, I get a yjs error `Position x out of range`.

After further investigation, I propose 2 fixes

### Upgrade y-prosemirror
The "surface level" error seems to be fixed here: https://github.com/yjs/y-prosemirror/releases/tag/v1.2.13. I'll update y-prosemirror in BlockNote for the next release

### Improve document creation
Document creation currently happens on the client side, if no existing document is returned from the server:

<img width="551" alt="image" src="https://github.com/user-attachments/assets/296ac9d5-804f-4d39-b6d5-df41d7834d7d">

This brings us to the root cause. Multiple clients can "initiate" a yjs document if no document is retrieved from the server. This is pretty dangerous, as both users will start from a different yjs document. Even though it's initiated from the same content, the internal ids in the yjs document will differ. This will cause yjs to have trouble syncing content and / or cursor selections.

#### Recommended fix:
The ideal way to initialize the document is at the same time when the metadata (like the title / creation date / owner) is inserted in the database. Would this be possible?

**Comment by AntoLC** [comment]
> Recommended fix:
> The ideal way to initialize the document is at the same time when the metadata (like the title / creation date / owner) is inserted in the database. Would this be possible?

I think we can, yes

**Comment by AntoLC** [comment]
The bug didn't seem to be about multiple creations with collaborators, having the initial content saved at the same time as the document didn't solve the problem.
It seems more something around how the initial document was builded, I have the feeling it must have some tiptap structures to fit with the system?
https://github.com/TypeCellOS/BlockNote/blob/71792c2fbdc99785cd8ce5b540d1a468e6c66131/packages/core/src/editor/BlockNoteTipTapEditor.ts#L73-L131

I proposed a fix (#484), using more the Blocknote way.
